### ISSUE TITLE
Попытаться интегрировать сервер

### ISSUE THREAD

**Issue by alexstrive** [microservices-course-itmo/deployer#23]
Необходимо связаться с командой разработки серверной части, и обсудить возможность интеграции. При наличии возможности интеграции - произвести её.

**Comment by alexstrive** [comment]
@MaximLukianchuk поговори с @Arthasasyan по данному поводу.

**Comment by Arthasasyan** [comment]
@MaximLukianchuk сегодня или завтра раскидаю ответственных за API, канал в слаке `recommendation-team-general`
